version: 1.0.{build}
environment:
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2013
      VS_VERSION: 2013      
      ADDITIONAL_CMAKE_ARGS: -DID_ALLOW_TOOLS=OFF -DID_UNICODE=ON
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      VS_VERSION: 2015
      QTDIR_MSVC2015_X86: C:/Qt/5.11.1/msvc2015
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      VS_VERSION: 2017
      QTDIR_MSVC2017_X86: C:/Qt/5.11.1/msvc2015      
build_script:
- cmd: >-
    cmake_msvc%VS_VERSION%.cmd %ADDITIONAL_CMAKE_ARGS%

    cd build/msvc%VS_VERSION%-x86

    cmake --build . --target dist --config Release

    cmake --build . --target sdk --config Release
artifacts:
- path: build/msvc%VS_VERSION%-x86/dist/*.zip
  name: fhDOOM